### PR TITLE
Unify all gamepad input types for easier handling of controller profiles

### PR DESCRIPTION
**Pull request by looki**

### CODE REVIEW

**Comment by LB--** [comment]
Too lazy to merge from the command line? :p

**Comment by looki** [comment]
Accepting pull requests just feels cooler!

**Comment by looki** [comment]
I actually ended up merging it from the command line because github's automatic merge kept some old code that broke the extension :(

**Comment by LB--** [comment]
Yeah I always do merges from the command line with the `--no-commit` option, and make sure the code still compiles and runs properly. Usually with complex merges the automatic merge will succeed but the resulting code will be wrong. If you use `--no-commit` you can make additional changes and then commit as normal to complete the merge.

**Comment by looki** [comment]
Yeah, it was stupid of me. I worked all day long and it was 4 AM, I just wanted to go to bed :smile:

**Comment by looki** [comment]
BTW, I really wish I'd be using Edif + a not ancient version of VS for this :/ Edif used to have trouble with sub-apps so I just went for rSDK. I remember reading you have fixed this bug at some point? Anyway at this point I just want to get things done so it's too late to switch anyway.

**Pull request merged**
